from __future__ import annotations

import asyncio
import json
import os
import threading
from dataclasses import asdict
from typing import Any, Dict, Optional
from pathlib import Path

import numpy as np
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from adcs_core.api import (
    ActuatorLimits,
    ActuatorState,
    AirspeedSensor,
    AircraftParameters,
    Altimeter,
    Autopilot,
    AutopilotTargets,
    Compass,
    ControlInputs,
    FailureManager,
    IMU,
    State,
    WindModel,
    analyze_modal_structure,
    compute_level_trim,
    compute_lqr_lateral,
    compute_lqr_longitudinal,
    design_lateral_lqr,
    design_longitudinal_lqr,
    derivatives_6dof,
    forces_and_moments_body,
    get_aircraft_model,
    linearize,
    post_step_sanitize,
    rk4_step,
    rotation_body_to_inertial,
)
from adcs_core.analysis.lqr_longitudinal import LONGITUDINAL_STATE_IDX_FULL, LONGITUDINAL_INPUT_IDX_FULL
from adcs_core.analysis.lqr_lateral import LATERAL_STATE_IDX_FULL, LATERAL_INPUT_IDX_FULL
from adcs_core.environment.dryden import DrydenTurbulence
from backend_api.workbench import (
    build_analysis_bundle,
    control_response,
    custom_aircraft_response,
    estimation_response,
    frequency_response,
    linearization_response,
    mode_shapes_response,
    serialize_model,
    step_response,
    trim_response,
    validation_response,
)

BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = BASE_DIR / "aircraft_simulator" / "frontend" / "out"
PLOTS_DIR = BASE_DIR / "plots"

app = FastAPI(title="Aircraft Simulator API", version="0.1.0")

# CORS origins can be configured via ALLOWED_ORIGINS (comma-separated).
_default_origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
_origins_env = os.getenv("ALLOWED_ORIGINS", "").strip()
_allowed_origins = [o.strip() for o in _origins_env.split(",") if o.strip()] if _origins_env else _default_origins

app.add_middleware(
    CORSMiddleware,
    allow_origins=_allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve frontend (+ plots generated by scripts)
if FRONTEND_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(FRONTEND_DIR), html=True), name="static")
if PLOTS_DIR.exists():
    app.mount("/static/plots", StaticFiles(directory=str(PLOTS_DIR), html=False), name="plots")


@app.get("/")
def root() -> FileResponse:
    index_path = FRONTEND_DIR / "index.html"
    if index_path.exists():
        return FileResponse(str(index_path))
    return {"error": "Frontend index.html not found"}


class SimRuntime:
    def __init__(self):
        self.lock = threading.Lock()

        self.selected_aircraft_id = "cessna_172r"
        self.params = AircraftParameters()
        self.limits = ActuatorLimits()

        self.state = State(x=0.0, y=0.0, z=-1000.0, u=35.0, v=0.0, w=0.0)
        self.t = 0.0
        self.dt = 0.02
        self.running = False

        self.targets = AutopilotTargets(airspeed_mps=35.0, altitude_m=1000.0, heading_rad=0.0)
        self.autopilot_enabled = True

        # Phase 11: LQR weights
        # Longitudinal weights [u, w, q, theta]
        self.Q_lon = np.diag([1.0, 10.0, 100.0, 50.0])
        self.R_lon = np.diag([1.0, 0.5])  # [elevator, throttle]

        # Lateral weights [v, p, r, phi]
        self.Q_lat = np.diag([1.0, 10.0, 10.0, 50.0])
        self.R_lat = np.diag([1.0, 1.0])  # [aileron, rudder]

        self.K_lon = np.zeros((2, 4))
        self.K_lat = np.zeros((2, 4))
        self.trim_x0 = self.state.as_vector()
        self.trim_u0 = np.array([0.5, 0.0, 0.0, 0.0]) # throttle, aileron, elevator, rudder

        self.act = ActuatorState(tau_s=0.15, limits=self.limits)
        self.act.reset(ControlInputs(throttle=0.5))
        self.failures = FailureManager()

        self.seed = 7
        self.wind = WindModel(steady_ned_mps=np.zeros(3), seed=self.seed)
        self.altimeter = Altimeter(seed=self.seed + 1)
        self.airspeed_sensor = AirspeedSensor(seed=self.seed + 2)
        self.compass = Compass(seed=self.seed + 3)
        self.imu = IMU(seed=self.seed + 4)

        self.turbulence_intensity = 0.1
        self.dryden = DrydenTurbulence(intensity=self.turbulence_intensity, seed=self.seed + 5)

        self.last_packet: Dict[str, Any] = {}
        
        # Initial trim and gain calculation
        self.recompute_gains()

    def recompute_gains(self) -> None:
        """
        Computes the LQR gains based on current aircraft and targets.
        """
        try:
            # 1. Trim for current target airspeed
            trim = compute_level_trim(self.targets.airspeed_mps, self.params, limits=self.limits)
            self.trim_x0 = trim.x0
            self.trim_u0 = trim.u0

            # 2. Linearize
            def f_sim(x, u_vec):
                ctrl = ControlInputs(throttle=u_vec[0], aileron=u_vec[1], elevator=u_vec[2], rudder=u_vec[3])
                return xdot_full(x, ctrl, params=self.params, limits=self.limits)
            
            A, B = linearize(f_sim, trim.x0, trim.u0)

            # 3. Design LQR
            design_lon = design_longitudinal_lqr(A, B, Q=self.Q_lon, R=self.R_lon)
            design_lat = design_lateral_lqr(A, B, Q=self.Q_lat, R=self.R_lat)

            self.K_lon = design_lon.K
            self.K_lat = design_lat.K
            
            # Reset state to trim (optional, but good for stability on change)
            # self.state = State.from_vector(trim.x0)
        except Exception as e:
            print(f"Error computing LQR gains: {e}")

    def select_aircraft(self, aircraft_id: str) -> Dict[str, Any]:
        model = get_aircraft_model(aircraft_id)
        with self.lock:
            self.selected_aircraft_id = model.id
            self.params = model.params
            self.limits = model.limits
            
            # Reset state for the new aircraft
            self.state = State(x=0.0, y=0.0, z=-1000.0, u=35.0, v=0.0, w=0.0)
            self.t = 0.0
            
            self.act = ActuatorState(tau_s=0.15, limits=self.limits)
            self.act.reset(ControlInputs(throttle=0.5))
            self.failures = FailureManager()
            
            self.recompute_gains()

        return {
            "id": model.id,
            "name": model.name,
            "classification": model.classification,
            "stability_mode": model.stability_mode,
        }

    def set_wind(self, n: float, e: float, d: float) -> None:
        with self.lock:
            self.wind.steady_ned_mps = np.array([n, e, d], dtype=float)

    def set_targets(self, V: Optional[float] = None, alt: Optional[float] = None, hdg_deg: Optional[float] = None) -> None:
        with self.lock:
            old_V = self.targets.airspeed_mps
            self.targets = AutopilotTargets(
                airspeed_mps=self.targets.airspeed_mps if V is None else float(V),
                altitude_m=self.targets.altitude_m if alt is None else float(alt),
                heading_rad=self.targets.heading_rad if hdg_deg is None else float(np.deg2rad(hdg_deg)),
            )
            # If airspeed target changed significantly, recompute gains
            if V is not None and abs(V - old_V) > 1.0:
                self.recompute_gains()

    def set_autopilot(self, enabled: bool) -> None:
        with self.lock:
            self.autopilot_enabled = bool(enabled)

    def set_turbulence(self, intensity: float) -> None:
        with self.lock:
            self.turbulence_intensity = float(np.clip(intensity, 0.0, 1.0))
            self.dryden.intensity = self.turbulence_intensity

    def step(self) -> Dict[str, Any]:
        with self.lock:
            s = self.state
            t = self.t
            dt = self.dt

            self.failures.step(t)

            params = self.params
            limits = self.limits

            # wind, body transform
            w_ned = self.wind.step(dt)
            C_bi = rotation_body_to_inertial(s.phi, s.theta, s.psi)
            w_body_steady = C_bi.T @ w_ned

            v_b = np.array([s.u, s.v, s.w], dtype=float)
            v_air_mps = float(np.linalg.norm(v_b - w_body_steady))
            w_body_turb = self.dryden.step(dt, -float(s.z), v_air_mps)

            v_air_b = v_b - w_body_steady - w_body_turb

            # Autopilot logic (Phase 11: LQR)
            u_cmd = ControlInputs(throttle=self.trim_u0[0], aileron=0.0, elevator=self.trim_u0[2], rudder=0.0)
            lqr_debug = {}
            
            if self.autopilot_enabled:
                # 1. Longitudinal LQR
                # States: [u, w, q, theta]
                x_lon = s.as_vector()[LONGITUDINAL_STATE_IDX_FULL]
                x_ref_lon = self.trim_x0[LONGITUDINAL_STATE_IDX_FULL].copy()
                
                # Altitude command -> pitch command using a simple outer loop or altitude state in LQR
                # For now, let's keep it simple: penalize theta vs trim.
                # To follow altitude, we'd need an augmented state or an outer PID.
                # Let's use an outer PID for altitude -> delta_theta as in Phase 2, but LQR for the rest.
                alt_err = self.targets.altitude_m - (-s.z)
                theta_cmd = np.clip(0.008 * alt_err, -0.3, 0.3)
                x_ref_lon[3] = theta_cmd 
                
                du_lon = -self.K_lon @ (x_lon - x_ref_lon) # [elevator, throttle]
                
                # 2. Lateral LQR
                # States: [v, p, r, phi]
                x_lat = s.as_vector()[LATERAL_STATE_IDX_FULL]
                x_ref_lat = self.trim_x0[LATERAL_STATE_IDX_FULL].copy()
                
                # Heading command -> bank command
                psi_err = float((self.targets.heading_rad - s.psi + np.pi) % (2.0 * np.pi) - np.pi)
                phi_cmd = np.clip(1.2 * psi_err, -0.6, 0.6)
                x_ref_lat[3] = phi_cmd
                
                du_lat = -self.K_lat @ (x_lat - x_ref_lat) # [aileron, rudder]
                
                u_cmd = ControlInputs(
                    throttle=float(np.clip(self.trim_u0[0] + du_lon[1], 0, 1)),
                    elevator=float(np.clip(self.trim_u0[2] + du_lon[0], -limits.elevator_max_rad, limits.elevator_max_rad)),
                    aileron=float(np.clip(du_lat[0], -limits.aileron_max_rad, limits.aileron_max_rad)),
                    rudder=float(np.clip(du_lat[1], -limits.rudder_max_rad, limits.rudder_max_rad))
                )
                lqr_debug = {
                    "delta_a": float(du_lat[0]),
                    "delta_r": float(du_lat[1]),
                    "delta_x_lat": (x_lat - x_ref_lat).tolist(),
                    "phi_deg": float(np.degrees(s.phi)),
                    "theta_cmd": float(theta_cmd),
                    "phi_cmd": float(phi_cmd),
                }

            u_cmd = self.failures.apply_actuator(u_cmd)
            u = self.act.update(u_cmd, dt)

            # dynamics
            def f_dyn(ti: float, xi: np.ndarray) -> np.ndarray:
                si = State.from_vector(xi)
                C_bi_i = rotation_body_to_inertial(si.phi, si.theta, si.psi)
                w_body_steady_i = C_bi_i.T @ w_ned
                v_b_i = np.array([si.u, si.v, si.w], dtype=float)
                v_air_b_i = v_b_i - w_body_steady_i - w_body_turb
                F, M, _ = forces_and_moments_body(si, u, params, limits, uvw_air_mps=v_air_b_i)
                return derivatives_6dof(ti, xi, params, F, M)

            x_next = rk4_step(f_dyn, t, s.as_vector(), dt)
            x_next = post_step_sanitize(x_next)
            self.state = State.from_vector(x_next)
            self.t = t + dt

            packet = {
                "t": float(self.t),
                "truth": {
                    "x": float(self.state.x),
                    "y": float(self.state.y),
                    "z": float(self.state.z),
                    "altitude_m": -float(self.state.z),
                    "phi": float(self.state.phi),
                    "theta": float(self.state.theta),
                    "psi": float(self.state.psi),
                    "u": float(self.state.u),
                    "v": float(self.state.v),
                    "w": float(self.state.w),
                },
                "wind_ned": {"n": float(w_ned[0]), "e": float(w_ned[1]), "d": float(w_ned[2])},
                "controls": {"cmd": asdict(u_cmd), "act": asdict(u)},
                "targets": {
                    "V": float(self.targets.airspeed_mps),
                    "alt": float(self.targets.altitude_m),
                    "hdg_deg": float(np.rad2deg(self.targets.heading_rad)),
                },
                "turbulence": {
                    "intensity": float(self.turbulence_intensity),
                    "gust_uvw": self.dryden.last_output.tolist(),
                },
                "ap": lqr_debug,
            }

            self.last_packet = packet
            return packet


runtime = SimRuntime()


@app.post("/api/v1/aircraft/select")
def select_aircraft(payload: Dict[str, Any]) -> Dict[str, Any]:
    aircraft_id = payload.get("aircraft_id") or payload.get("id")
    if not aircraft_id:
        return {"error": "Missing 'aircraft_id' in request body."}
    try:
        meta = runtime.select_aircraft(str(aircraft_id))
        model = get_aircraft_model(str(aircraft_id))
    except KeyError as exc:
        return {"error": str(exc)}
    return {**serialize_model(model), "selected_aircraft": meta}


@app.post("/api/v1/analysis/trim")
def compute_trim(payload: Dict[str, Any]) -> Dict[str, Any]:
    try:
        bundle = build_analysis_bundle(payload, current_model=get_aircraft_model(runtime.selected_aircraft_id))
        return trim_response(bundle)
    except Exception as e:
        return {"error": str(e)}


@app.post("/api/v1/analysis/linearize")
def compute_linearization(payload: Dict[str, Any]) -> Dict[str, Any]:
    try:
        bundle = build_analysis_bundle(payload, current_model=get_aircraft_model(runtime.selected_aircraft_id))
        return linearization_response(bundle)
    except Exception as e:
        return {"error": str(e)}


@app.post("/api/v1/analysis/control")
def compute_control_analysis(payload: Dict[str, Any]) -> Dict[str, Any]:
    try:
        return control_response(payload, current_model=get_aircraft_model(runtime.selected_aircraft_id))
    except Exception as e:
        return {"error": str(e)}

@app.post("/api/v1/analysis/step-response")
def compute_step_response(payload: Dict[str, Any]) -> Dict[str, Any]:
    try:
        return step_response(payload, current_model=get_aircraft_model(runtime.selected_aircraft_id))
    except Exception as e:
        return {"error": str(e)}


@app.post("/api/v1/estimation/run")
def run_estimation(payload: Dict[str, Any]) -> Dict[str, Any]:
    try:
        return estimation_response(payload, current_model=get_aircraft_model(runtime.selected_aircraft_id))
    except Exception as e:
        return {"error": str(e)}


@app.post("/api/v1/analysis/frequency-response")
def compute_frequency_response(payload: Dict[str, Any]) -> Dict[str, Any]:
    try:
        return frequency_response(payload, current_model=get_aircraft_model(runtime.selected_aircraft_id))
    except Exception as e:
        return {"error": str(e)}


@app.post("/api/v1/analysis/mode-shapes")
def compute_mode_shapes(payload: Dict[str, Any]) -> Dict[str, Any]:
    try:
        return mode_shapes_response(payload, current_model=get_aircraft_model(runtime.selected_aircraft_id))
    except Exception as e:
        return {"error": str(e)}


@app.post("/api/v1/validation/run")
def run_validation(payload: Dict[str, Any]) -> Dict[str, Any]:
    try:
        return validation_response(payload, current_model=get_aircraft_model(runtime.selected_aircraft_id))
    except Exception as e:
        return {"error": str(e)}

@app.websocket("/ws")
async def ws_endpoint(ws: WebSocket):
    await ws.accept()
    try:
        while True:
            # non-blocking receive for commands
            try:
                msg = await asyncio.wait_for(ws.receive_text(), timeout=0.0)
                data = json.loads(msg)
                _handle_command(data)
            except asyncio.TimeoutError:
                pass

            pkt = runtime.step()
            await ws.send_text(json.dumps(pkt))
            await asyncio.sleep(runtime.dt)
    except WebSocketDisconnect:
        return


def _handle_command(data: Dict[str, Any]) -> None:
    t = data.get("type")
    if t == "set_targets":
        runtime.set_targets(V=data.get("V"), alt=data.get("alt"), hdg_deg=data.get("hdg_deg"))
    elif t == "set_wind":
        runtime.set_wind(float(data.get("n", 0.0)), float(data.get("e", 0.0)), float(data.get("d", 0.0)))
    elif t == "set_turbulence":
        runtime.set_turbulence(float(data.get("intensity", 0.0)))
    elif t == "set_autopilot":
        runtime.set_autopilot(bool(data.get("enabled", True)))
